mode: "train"
experiment_name: "02_finetune_AV_Fusion__base_en"
training:
  epochs: 8
  start_epoch: 0
  work_dir: './experiments/base.en'
  train_av_fusion: True
  train_whisper: False
  lr: 0.0001
  lr_decay_per_epoch: 0.0
  log_frequency: 250
  lossfactor_mel: 1.0
  lossfactor_audiofeatures: 2.0
  lossfactor_decoder: 2.0
dataset:
  lrs3_prep_dir: "/nfs/scratch/staff/simicch/00_data/02_LRS3/prep_test_repo"
  lrs3_lists_path: "/nfs/scratch/staff/simicch/00_data/02_LRS3/prep_test_repo"
  lrs3_filelist_training: "trainval_train"
  lrs3_filelist_validation: "trainval_valid"
  validation_num_examples: 1000
  lrs3_audio_dir: "/nfs/scratch/staff/simicch/00_data/02_LRS3/prep_test_repo/audio"
  lrs3_video_dir: "/nfs/scratch/staff/simicch/00_data/02_LRS3/prep_test_repo/cropped_videos_3ddfaV2"
  musan_prep_dir: "/nfs/scratch/staff/simicch/00_data/03_musan/prep_repo"
  musan_type: "all"
  SNR_range_training: [-20, 50]
  SNR_range_valid: [-10, 10]
  batchsize_training: 8
  batchsize_valid: 2
  specaug_flag: True
  specaug_sequmaxlen: 100
  specaug_maxlenratio: 0.3
  specaug_maxchannels: 27
  maxLenVideo: 750        # 30*25
  frameCropShape: [88,88]
  flipProb: 0.5
  erasingProb: 0.5
  eraseSizeRange: [2, 30]
  eraseRatioRange: [0.3, 3.3]
  timeMaskRange: [0, 10]
model:
  AV_Fusion_attLayer: 12
  AV_Fusion_attHeads: 12
  AV_Fusion_blocksize: 160
  AV_Fusion_inp_dim: 80
  AV_Fusion_proc_dim: 80
  AV_Fusion_out_dim: 80
  Specfront_procChannels: 128
  Specfront_layerNum: 7
  Specfront_inp_dim: 80
  Specfront_out_dim: 80
  Lipnet_video_layer: [[2,1],[2,1],[2,1],[3,1]]
  Lipnet_emb_size: 80
  whisper_model: 'base.en'
  max_tokens: 
  whisper_chkp: 
  AV_Fusion_chkp: 'path_to_AV_Fusion_Module_checkpoint after training base_en__train01_pretrain_AV_Fusion.yaml'


