mode: "train"
experiment_name: "03a_finetune_AV_Fusion__small_en"
training:
  epochs: 20
  start_epoch: 8
  work_dir: './experiments/small.en'
  train_av_fusion: True
  train_whisper: True
  lr: 0.000015849
  lr_decay_per_epoch: 1.5849
  log_frequency: 250
  lossfactor_mel: 1.0
  lossfactor_audiofeatures: 2.0
  lossfactor_decoder: 2.0
dataset:
  lrs3_prep_dir: 'path_to_lrs3'
  lrs3_lists_path: 'path_to_lrs3_file.lists'
  lrs3_filelist_training: "trainval_train"
  lrs3_filelist_validation: "trainval_valid"
  validation_num_examples: 1000
  lrs3_audio_dir: 'path_to_audio_files'
  lrs3_video_dir: 'path_to_cropped_video_files'
  musan_prep_dir: 'path_to_prepared_musan'
  musan_type: "all"
  SNR_range_training: [-20, 50]
  SNR_range_valid: [-10, 10]
  batchsize_training: 8
  batchsize_valid: 2
  specaug_flag: True
  specaug_sequmaxlen: 100
  specaug_maxlenratio: 0.3
  specaug_maxchannels: 27
  maxLenVideo: 750        # 30*25
  frameCropShape: [88,88]
  flipProb: 0.5
  erasingProb: 0.5
  eraseSizeRange: [2, 30]
  eraseRatioRange: [0.3, 3.3]
  timeMaskRange: [0, 10]
model:
  AV_Fusion_attLayer: 12
  AV_Fusion_attHeads: 12
  AV_Fusion_blocksize: 160
  AV_Fusion_inp_dim: 80
  AV_Fusion_proc_dim: 80
  AV_Fusion_out_dim: 80
  Specfront_procChannels: 128
  Specfront_layerNum: 7
  Specfront_inp_dim: 80
  Specfront_out_dim: 80
  Lipnet_video_layer: [[2,1],[2,1],[2,1],[3,1]]
  Lipnet_emb_size: 80
  whisper_model: 'small.en'
  max_tokens: 
  whisper_chkp: 
  AV_Fusion_chkp: 'path_to_AV_Fusion_Module_checkpoint after training small_en__train02_finetune_AV_Fusion.yaml'


