mode: "test"
experiment_name: "test_01_finetune_FusionOnly__small_en__whisperTrain"
test:
  work_dir: './experiments/small.en'
  batchsize: 8
  noise_categories: ['babble', 'music', 'noise', 'lrs3_sidespeaker']
  SNR_values: [10, 5, 0, -5, -10]
dataset:
  lrs3_prep_dir: 'path_to_lrs3'
  lrs3_lists_path: 'path_to_lrs3_file.lists'
  lrs3_filelist: "test"
  lrs3_audio_dir: 'path_to_audio_files'
  lrs3_video_dir: 'path_to_cropped_video_files'
  musan_prep_dir: 'path_to_prepared_musan'
  frameCropShape: [88,88]
model:
  AV_Fusion_attLayer: 12
  AV_Fusion_attHeads: 12
  AV_Fusion_blocksize: 160
  AV_Fusion_inp_dim: 80
  AV_Fusion_proc_dim: 80
  AV_Fusion_out_dim: 80
  Specfront_procChannels: 128
  Specfront_layerNum: 7
  Specfront_inp_dim: 80
  Specfront_out_dim: 80
  Lipnet_video_layer: [[2,1],[2,1],[2,1],[3,1]]
  Lipnet_emb_size: 80
  whisper_model: 'small.en'
  max_tokens: 
  whisper_chkp: 
  AV_Fusion_chkp: 'path_to_AV_Fusion_Module_checkpoint'


